function h = h(in1,in2,in3,in4)
%H
%    H = H(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    08-Oct-2025 07:08:35

n_a1 = in3(1,:);
n_a2 = in3(2,:);
n_a3 = in3(3,:);
n_t1 = in4(1,:);
n_t2 = in4(2,:);
n_t3 = in4(3,:);
u4 = in2(4,:);
u5 = in2(5,:);
u6 = in2(6,:);
u7 = in2(7,:);
x_new1 = in1(1,:);
x_new2 = in1(2,:);
x_new3 = in1(3,:);
x_new4 = in1(4,:);
x_new8 = in1(8,:);
x_new9 = in1(9,:);
x_new10 = in1(10,:);
t2 = x_new1.^2;
t3 = x_new2.^2;
t4 = x_new3.^2;
t5 = x_new4.^2;
t6 = x_new1.*x_new2.*2.0;
t7 = x_new1.*x_new3.*2.0;
t8 = x_new1.*x_new4.*2.0;
t9 = x_new2.*x_new3.*2.0;
t10 = x_new2.*x_new4.*2.0;
t11 = x_new3.*x_new4.*2.0;
t12 = -t10;
t13 = -t3;
t14 = -t4;
t15 = -t5;
t16 = t6+t11;
t17 = t7+t12;
t18 = t2+t5+t13+t14;
h = [n_a1+x_new8+t17.*u7;n_a2+x_new9-t16.*u7;n_a3+x_new10-t18.*u7;n_t1+u4.*(t2+t3+t14+t15)+u5.*(t8+t9)-t17.*u6;n_t2+u5.*(t2+t4+t13+t15)+t16.*u6-u4.*(t8-t9);n_t3+u4.*(t7+t10)+t18.*u6-u5.*(t6-t11)];
