function H = H_ekf(in1,in2)
%H_ekf
%    H = H_ekf(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    09-Oct-2025 11:28:59

u4 = in2(4,:);
u5 = in2(5,:);
u6 = in2(6,:);
u7 = in2(7,:);
x_new1 = in1(1,:);
x_new2 = in1(2,:);
x_new3 = in1(3,:);
x_new4 = in1(4,:);
t2 = u4.*x_new1.*2.0;
t3 = u4.*x_new2.*2.0;
t4 = u5.*x_new1.*2.0;
t5 = u4.*x_new3.*2.0;
t6 = u5.*x_new2.*2.0;
t7 = u6.*x_new1.*2.0;
t8 = u4.*x_new4.*2.0;
t9 = u5.*x_new3.*2.0;
t10 = u6.*x_new2.*2.0;
t11 = u7.*x_new1.*2.0;
t12 = u5.*x_new4.*2.0;
t13 = u6.*x_new3.*2.0;
t14 = u7.*x_new2.*2.0;
t15 = u6.*x_new4.*2.0;
t16 = u7.*x_new3.*2.0;
t17 = u7.*x_new4.*2.0;
t18 = -t6;
t19 = -t8;
t20 = -t11;
t21 = -t13;
t22 = -t14;
t23 = -t17;
t24 = t3+t9+t15;
t25 = t5+t7+t18;
t26 = t4+t10+t19;
t27 = t2+t12+t21;
H = reshape([t16,t22,t20,t27,t26,t25,t23,t20,t14,t24,t25,-t4+t8-t10,t11,t23,t16,-t5+t6-t7,t24,t27,t22,-t16,t23,t26,-t2-t12+t13,t24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0],[6,10]);
