function l = l(in1)
%L
%    L = L(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    08-Oct-2025 07:08:36

x_new1 = in1(1,:);
x_new2 = in1(2,:);
x_new3 = in1(3,:);
x_new4 = in1(4,:);
x_new5 = in1(5,:);
x_new6 = in1(6,:);
x_new7 = in1(7,:);
x_new8 = in1(8,:);
x_new9 = in1(9,:);
x_new10 = in1(10,:);
t2 = abs(x_new1);
t3 = abs(x_new2);
t4 = abs(x_new3);
t5 = abs(x_new4);
t6 = t2.^2;
t7 = t3.^2;
t8 = t4.^2;
t9 = t5.^2;
t10 = t6+t7+t8+t9;
t11 = 1.0./sqrt(t10);
l = [t11.*x_new1;t11.*x_new2;t11.*x_new3;t11.*x_new4;x_new5;x_new6;x_new7;x_new8;x_new9;x_new10];
