function h = h(in1,in2,in3)
%H
%    H = H(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    04-Dec-2025 12:03:32

n_a1 = in3(1,:);
n_a2 = in3(2,:);
n_a3 = in3(3,:);
u4 = in2(4,:);
x_new1 = in1(1,:);
x_new2 = in1(2,:);
x_new3 = in1(3,:);
x_new4 = in1(4,:);
x_new8 = in1(8,:);
x_new9 = in1(9,:);
x_new10 = in1(10,:);
h = [n_a1+x_new8+u4.*(x_new1.*x_new3.*2.0-x_new2.*x_new4.*2.0);n_a2+x_new9-u4.*(x_new1.*x_new2.*2.0+x_new3.*x_new4.*2.0);n_a3+x_new10-u4.*(x_new1.^2-x_new2.^2-x_new3.^2+x_new4.^2)];
