function H = H_ekf(in1,in2)
%H_ekf
%    H = H_ekf(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    04-Dec-2025 12:03:32

u4 = in2(4,:);
x_new1 = in1(1,:);
x_new2 = in1(2,:);
x_new3 = in1(3,:);
x_new4 = in1(4,:);
t2 = u4.*x_new1.*2.0;
t3 = u4.*x_new2.*2.0;
t4 = u4.*x_new3.*2.0;
t5 = u4.*x_new4.*2.0;
t6 = -t2;
t7 = -t3;
t8 = -t5;
H = reshape([t4,t7,t6,t8,t6,t3,t2,t8,t4,t7,-t4,t8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0],[3,10]);
