function M = M_ekf(in1,in2)
%M_ekf
%    M = M_ekf(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    04-Dec-2025 12:03:32

M = reshape([1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0],[3,3]);
